
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.PageContent.Models
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{059f8915-49a2-45df-ae13-deb58f60ae4b}", "", "Feature.PageContent")]
    [SitecoreType(TemplateId = Helix.Feature.PageContent.Templates.Hero.TemplateIdString)]
	public partial interface IHero : IGlassBase
	{
		
		/// <summary>Represents the  field (951b21e4-450f-44f8-81dc-233b3fc9c548).</summary>
        [SitecoreField(FieldName = Helix.Feature.PageContent.Templates.Hero.Fields.Button_FieldName)]
		Link Button { get; }

		/// <summary>Represents the  field (42581a24-37b1-4f71-b6d7-acf88125580e).</summary>
        [SitecoreField(FieldName = Helix.Feature.PageContent.Templates.Hero.Fields.Heading_FieldName)]
		string Heading { get; }

		/// <summary>Represents the  field (c6ec5294-f154-4842-aae4-131aa6bccdbe).</summary>
        [SitecoreField(FieldName = Helix.Feature.PageContent.Templates.Hero.Fields.LeadInTitle_FieldName)]
		string LeadInTitle { get; }

	}

}

namespace Helix.Feature.PageContent.Models
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{0aec13f0-984e-4c21-86f7-18bd23d4300b}", "", "Feature.PageContent")]
    [SitecoreType(TemplateId = Helix.Feature.PageContent.Templates.SectionHeader.TemplateIdString)]
	public partial interface ISectionHeader : IGlassBase
	{
		
		/// <summary>Represents the Description field (8320bc26-e1fc-4dc2-9a5c-278c47ae4d03).</summary>
        [SitecoreField(FieldName = Helix.Feature.PageContent.Templates.SectionHeader.Fields.HeaderDescription_FieldName)]
		string HeaderDescription { get; }

		/// <summary>Represents the Title field (b3004ac2-1513-4134-abed-b9bd55c45df6).</summary>
        [SitecoreField(FieldName = Helix.Feature.PageContent.Templates.SectionHeader.Fields.HeaderTitle_FieldName)]
		string HeaderTitle { get; }

	}

}




namespace Helix.Feature.PageContent
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct Hero
		{
            public const string TemplateIdString = "059f8915-49a2-45df-ae13-deb58f60ae4b";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Button = new ID("951b21e4-450f-44f8-81dc-233b3fc9c548");
				public const string Button_FieldName = "Button";

				public static readonly ID Heading = new ID("42581a24-37b1-4f71-b6d7-acf88125580e");
				public const string Heading_FieldName = "Heading";

				public static readonly ID LeadInTitle = new ID("c6ec5294-f154-4842-aae4-131aa6bccdbe");
				public const string LeadInTitle_FieldName = "LeadInTitle";

			}
		}

		public struct SectionHeader
		{
            public const string TemplateIdString = "0aec13f0-984e-4c21-86f7-18bd23d4300b";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID HeaderDescription = new ID("8320bc26-e1fc-4dc2-9a5c-278c47ae4d03");
				public const string HeaderDescription_FieldName = "HeaderDescription";

				public static readonly ID HeaderTitle = new ID("b3004ac2-1513-4134-abed-b9bd55c45df6");
				public const string HeaderTitle_FieldName = "HeaderTitle";

			}
		}

	}
}

// Helix.Feature.PageContent.Hero (/sitecore/templates/feature/PageContent/_Hero 059f8915-49a2-45df-ae13-deb58f60ae4b)
	// Button (951b21e4-450f-44f8-81dc-233b3fc9c548)
		// Type: General Link
		// Section: Information
		// Sort Order: 300
		// Source: 
	// Heading (42581a24-37b1-4f71-b6d7-acf88125580e)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 200
		// Source: 
	// LeadInTitle (c6ec5294-f154-4842-aae4-131aa6bccdbe)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 100
		// Source: 

// Helix.Feature.PageContent.SectionHeader (/sitecore/templates/feature/PageContent/_SectionHeader 0aec13f0-984e-4c21-86f7-18bd23d4300b)
	// HeaderDescription (8320bc26-e1fc-4dc2-9a5c-278c47ae4d03)
		// Type: Multi-Line Text
		// Section: Header Information
		// Sort Order: 200
		// Source: 
	// HeaderTitle (b3004ac2-1513-4134-abed-b9bd55c45df6)
		// Type: Single-Line Text
		// Section: Header Information
		// Sort Order: 100
		// Source: 

