---
ID: "eda4de90-fb88-45be-afc0-b98e0593b4b1"
Parent: "51e1374a-c4a6-45db-b431-cd2a7c57c1c6"
Template: "51e1374a-c4a6-45db-b431-cd2a7c57c1c6"
Path: /sitecore/templates/feature/projects/_ProjectCollection/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180311T171906Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
