
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Structural
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{a6d260be-e659-46bd-9f28-19d198e962c2}", "", "Feature.Structural")]
    [SitecoreType(TemplateId = Helix.Feature.Structural.Templates.ParametersTemplateGridSettings.TemplateIdString)]
	public partial interface IParametersTemplateGridSettings : IGlassBase
	{
		
		/// <summary>Represents the  field (51d5f220-aa4c-4617-b73d-0d682e88b444).</summary>
        [SitecoreField(FieldName = Helix.Feature.Structural.Templates.ParametersTemplateGridSettings.Fields.Classes_FieldName)]
		string Classes { get; }

		/// <summary>Represents the Element Id field (3bfdaee8-0ced-4efd-bfef-3b4de945e31e).</summary>
        [SitecoreField(FieldName = Helix.Feature.Structural.Templates.ParametersTemplateGridSettings.Fields.ElementId_FieldName)]
		string ElementId { get; }

	}

}




namespace Helix.Feature.Structural
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct ParametersTemplateGridSettings
		{
            public const string TemplateIdString = "a6d260be-e659-46bd-9f28-19d198e962c2";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Classes = new ID("51d5f220-aa4c-4617-b73d-0d682e88b444");
				public const string Classes_FieldName = "Classes";

				public static readonly ID ElementId = new ID("3bfdaee8-0ced-4efd-bfef-3b4de945e31e");
				public const string ElementId_FieldName = "ElementId";

			}
		}

	}
}

// Helix.Feature.Structural.ParametersTemplateGridSettings (/sitecore/templates/feature/Structural/ParametersTemplate_GridSettings a6d260be-e659-46bd-9f28-19d198e962c2)
	// Classes (51d5f220-aa4c-4617-b73d-0d682e88b444)
		// Type: Single-Line Text
		// Section: Component Settings
		// Sort Order: 200
		// Source: 
	// ElementId (3bfdaee8-0ced-4efd-bfef-3b4de945e31e)
		// Type: Single-Line Text
		// Section: Component Settings
		// Sort Order: 100
		// Source: 

