---
ID: "b7f4b7c3-19ca-4883-88bb-92c2ef7e8889"
Parent: "a6d260be-e659-46bd-9f28-19d198e962c2"
Template: "a6d260be-e659-46bd-9f28-19d198e962c2"
Path: /sitecore/templates/feature/Structural/ParametersTemplate_GridSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180214T015704Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
