
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Metadata.Models
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{82a8eec9-a4c6-48b3-9b43-7bc18ddd9e5e}", "", "Feature.Metadata")]
    [SitecoreType(TemplateId = Helix.Feature.Metadata.Templates.MetaTags.TemplateIdString)]
	public partial interface IMetaTags : IGlassBase
	{
		
		/// <summary>Represents the Description field (1983a8f5-7d6b-45be-8f9e-968e94c63753).</summary>
        [SitecoreField(FieldName = Helix.Feature.Metadata.Templates.MetaTags.Fields.MetaDescription_FieldName)]
		string MetaDescription { get; }

		/// <summary>Represents the Keywords field (4536c633-7f18-445f-9bbf-71da9aba2d54).</summary>
        [SitecoreField(FieldName = Helix.Feature.Metadata.Templates.MetaTags.Fields.MetaKeywords_FieldName)]
		string MetaKeywords { get; }

		/// <summary>Represents the Robots No Index field (864e298f-05c3-482f-8fbf-25b0d781f718).</summary>
        [SitecoreField(FieldName = Helix.Feature.Metadata.Templates.MetaTags.Fields.MetaNoIndex_FieldName)]
		bool MetaNoIndex { get; }

		/// <summary>Represents the Title field (c55fd8c7-f030-40c0-83ab-c046244a7689).</summary>
        [SitecoreField(FieldName = Helix.Feature.Metadata.Templates.MetaTags.Fields.MetaTitle_FieldName)]
		string MetaTitle { get; }

	}

}




namespace Helix.Feature.Metadata
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct MetaTags
		{
            public const string TemplateIdString = "82a8eec9-a4c6-48b3-9b43-7bc18ddd9e5e";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID MetaDescription = new ID("1983a8f5-7d6b-45be-8f9e-968e94c63753");
				public const string MetaDescription_FieldName = "MetaDescription";

				public static readonly ID MetaKeywords = new ID("4536c633-7f18-445f-9bbf-71da9aba2d54");
				public const string MetaKeywords_FieldName = "MetaKeywords";

				public static readonly ID MetaNoIndex = new ID("864e298f-05c3-482f-8fbf-25b0d781f718");
				public const string MetaNoIndex_FieldName = "MetaNoIndex";

				public static readonly ID MetaTitle = new ID("c55fd8c7-f030-40c0-83ab-c046244a7689");
				public const string MetaTitle_FieldName = "MetaTitle";

			}
		}

	}
}

// Helix.Feature.Metadata.MetaTags (/sitecore/templates/feature/metadata/_MetaTags 82a8eec9-a4c6-48b3-9b43-7bc18ddd9e5e)
	// MetaDescription (1983a8f5-7d6b-45be-8f9e-968e94c63753)
		// Type: Multi-Line Text
		// Section: Meta Information
		// Sort Order: 200
		// Source: 
	// MetaKeywords (4536c633-7f18-445f-9bbf-71da9aba2d54)
		// Type: Multi-Line Text
		// Section: Meta Information
		// Sort Order: 300
		// Source: 
	// MetaNoIndex (864e298f-05c3-482f-8fbf-25b0d781f718)
		// Type: Checkbox
		// Section: Meta Information
		// Sort Order: 400
		// Source: 
	// MetaTitle (c55fd8c7-f030-40c0-83ab-c046244a7689)
		// Type: Single-Line Text
		// Section: Meta Information
		// Sort Order: 100
		// Source: 

