
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Projects.Models
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{07ef3625-2856-4c66-a9a6-ac31216a56a6}", "", "Feature.Projects")]
    [SitecoreType(TemplateId = Helix.Feature.Projects.Templates.Project.TemplateIdString)]
	public partial interface IProject : IGlassBase
	{
		
		/// <summary>Represents the  field (7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.FullText_FieldName)]
		string FullText { get; }

		/// <summary>Represents the  field (0eb2de30-2d40-4f3a-a781-8e8efe96d2f0).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.Name_FieldName)]
		string Name { get; }

		/// <summary>Represents the  field (616279a1-24f9-43e5-bb4c-5ce2da6269e9).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.PrimaryImage_FieldName)]
		Image PrimaryImage { get; }

		/// <summary>Represents the  field (b3711e42-e538-4982-bcc5-0a0b6d44ffc7).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.ProjectType_FieldName)]
		string ProjectType { get; }

		/// <summary>Represents the  field (a8afcc63-4732-43d7-a426-1e9c0d683eea).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.Summary_FieldName)]
		string Summary { get; }

		/// <summary>Represents the  field (370db987-b2b2-4b02-8ed1-abb7ab22fd09).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.Project.Fields.ThumbImage_FieldName)]
		Image ThumbImage { get; }

	}

}

namespace Helix.Feature.Projects.Models
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{51e1374a-c4a6-45db-b431-cd2a7c57c1c6}", "", "Feature.Projects")]
    [SitecoreType(TemplateId = Helix.Feature.Projects.Templates.ProjectCollection.TemplateIdString)]
	public partial interface IProjectCollection : IGlassBase
	{
		
		/// <summary>Represents the  field (13a331f7-e588-4768-b2aa-a140de6335b6).</summary>
        [SitecoreField(FieldName = Helix.Feature.Projects.Templates.ProjectCollection.Fields.Projects_FieldName)]
		IEnumerable<Guid> Projects { get; }

	}

}




namespace Helix.Feature.Projects
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct Project
		{
            public const string TemplateIdString = "07ef3625-2856-4c66-a9a6-ac31216a56a6";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID FullText = new ID("7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87");
				public const string FullText_FieldName = "FullText";

				public static readonly ID Name = new ID("0eb2de30-2d40-4f3a-a781-8e8efe96d2f0");
				public const string Name_FieldName = "Name";

				public static readonly ID PrimaryImage = new ID("616279a1-24f9-43e5-bb4c-5ce2da6269e9");
				public const string PrimaryImage_FieldName = "PrimaryImage";

				public static readonly ID ProjectType = new ID("b3711e42-e538-4982-bcc5-0a0b6d44ffc7");
				public const string ProjectType_FieldName = "ProjectType";

				public static readonly ID Summary = new ID("a8afcc63-4732-43d7-a426-1e9c0d683eea");
				public const string Summary_FieldName = "Summary";

				public static readonly ID ThumbImage = new ID("370db987-b2b2-4b02-8ed1-abb7ab22fd09");
				public const string ThumbImage_FieldName = "ThumbImage";

			}
		}

		public struct ProjectCollection
		{
            public const string TemplateIdString = "51e1374a-c4a6-45db-b431-cd2a7c57c1c6";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Projects = new ID("13a331f7-e588-4768-b2aa-a140de6335b6");
				public const string Projects_FieldName = "Projects";

			}
		}

	}
}

// Helix.Feature.Projects.Project (/sitecore/templates/feature/projects/_Project 07ef3625-2856-4c66-a9a6-ac31216a56a6)
	// FullText (7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87)
		// Type: Rich Text
		// Section: Project Information
		// Sort Order: 300
		// Source: 
	// Name (0eb2de30-2d40-4f3a-a781-8e8efe96d2f0)
		// Type: Single-Line Text
		// Section: Project Information
		// Sort Order: 100
		// Source: 
	// PrimaryImage (616279a1-24f9-43e5-bb4c-5ce2da6269e9)
		// Type: Image
		// Section: Project Information
		// Sort Order: 500
		// Source: 
	// ProjectType (b3711e42-e538-4982-bcc5-0a0b6d44ffc7)
		// Type: Droplist
		// Section: Project Information
		// Sort Order: 600
		// Source: 
	// Summary (a8afcc63-4732-43d7-a426-1e9c0d683eea)
		// Type: Multi-Line Text
		// Section: Project Information
		// Sort Order: 200
		// Source: 
	// ThumbImage (370db987-b2b2-4b02-8ed1-abb7ab22fd09)
		// Type: Image
		// Section: Project Information
		// Sort Order: 400
		// Source: 

// Helix.Feature.Projects.ProjectCollection (/sitecore/templates/feature/projects/_ProjectCollection 51e1374a-c4a6-45db-b431-cd2a7c57c1c6)
	// Projects (13a331f7-e588-4768-b2aa-a140de6335b6)
		// Type: Treelist
		// Section: Information
		// Sort Order: 100
		// Source: 

