---
ID: "1efdc333-2629-4296-87af-9bef4d0dd525"
Parent: "955bac9c-13c6-4258-9a26-376da8f30592"
Template: "955bac9c-13c6-4258-9a26-376da8f30592"
Path: /sitecore/templates/feature/navigation/_NavigationItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180414T152920Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
