---
ID: "11123094-5707-41db-a840-66708448e66c"
Parent: "f3d4c94f-d401-43ac-94e8-49ac622ad7ef"
Template: "f3d4c94f-d401-43ac-94e8-49ac622ad7ef"
Path: /sitecore/templates/project/Agency/Page Types/Member/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180423T143722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
