
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Projects
{
	using global::Sitecore.ContentSearch;
	using global::Sitecore.Data;
	using global::Sitecore.Data.Items;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{07ef3625-2856-4c66-a9a6-ac31216a56a6}", "", "Feature.Projects")]
    [SitecoreType]
	public interface IProject : IGlassBase
	{
		
		/// <summary>Represents the  field (7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87).</summary>
		[IndexFieldAttribute("fulltext_t")]
		IRichTextField FullText { get; }

		/// <summary>Represents the  field (0eb2de30-2d40-4f3a-a781-8e8efe96d2f0).</summary>
		[IndexFieldAttribute("name_t")]
		ITextField Name { get; }

		/// <summary>Represents the  field (616279a1-24f9-43e5-bb4c-5ce2da6269e9).</summary>
		[IndexFieldAttribute("primaryimage")]
		IImageField PrimaryImage { get; }

		/// <summary>Represents the  field (b3711e42-e538-4982-bcc5-0a0b6d44ffc7).</summary>
		[IndexFieldAttribute("projecttype")]
		ITextField ProjectType { get; }

		/// <summary>Represents the  field (a8afcc63-4732-43d7-a426-1e9c0d683eea).</summary>
		[IndexFieldAttribute("summary_t")]
		ITextField Summary { get; }

		/// <summary>Represents the  field (370db987-b2b2-4b02-8ed1-abb7ab22fd09).</summary>
		[IndexFieldAttribute("thumbimage")]
		IImageField ThumbImage { get; }

	}

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	public class Project : IGlassBase, IProject
	{
		public Project(Item innerItem) : base(innerItem)
		{
		}

		public Project(IDictionary<string, string> searchFields) : base(searchFields)
		{
		}

		/// <summary>The name of the Sitecore Template that this class represents</summary>
		public static string TemplateName => "_Project";

		/// <summary>The ID of the Sitecore Template that this class represents</summary>
		public static ID ItemTemplateId => new ID("{07ef3625-2856-4c66-a9a6-ac31216a56a6}");

		/// <summary>The ID of the Sitecore Template that this class represents</summary>
		public override ID TemplateId => ItemTemplateId;

		
		private RichTextField _fullText;
		/// <summary>Represents the  field (7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87).</summary>
		[IndexFieldAttribute("fulltext_t")]
		public RichTextField FullText => _fullText ?? (_fullText = new RichTextField(new LazyField(() => InnerItem.Fields["{7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87}"], "/sitecore/templates/feature/projects/_Project", "FullText"), GetSearchFieldValue("fulltext_t")));
		

		private TextField _name;
		/// <summary>Represents the  field (0eb2de30-2d40-4f3a-a781-8e8efe96d2f0).</summary>
		[IndexFieldAttribute("name_t")]
		public TextField Name => _name ?? (_name = new TextField(new LazyField(() => InnerItem.Fields["{0eb2de30-2d40-4f3a-a781-8e8efe96d2f0}"], "/sitecore/templates/feature/projects/_Project", "Name"), GetSearchFieldValue("name_t")));
		

		private ImageField _primaryImage;
		/// <summary>Represents the  field (616279a1-24f9-43e5-bb4c-5ce2da6269e9).</summary>
		[IndexFieldAttribute("primaryimage")]
		public ImageField PrimaryImage => _primaryImage ?? (_primaryImage = new ImageField(new LazyField(() => InnerItem.Fields["{616279a1-24f9-43e5-bb4c-5ce2da6269e9}"], "/sitecore/templates/feature/projects/_Project", "PrimaryImage"), GetSearchFieldValue("primaryimage")));
		

		private TextField _projectType;
		/// <summary>Represents the  field (b3711e42-e538-4982-bcc5-0a0b6d44ffc7).</summary>
		[IndexFieldAttribute("projecttype")]
		public TextField ProjectType => _projectType ?? (_projectType = new TextField(new LazyField(() => InnerItem.Fields["{b3711e42-e538-4982-bcc5-0a0b6d44ffc7}"], "/sitecore/templates/feature/projects/_Project", "ProjectType"), GetSearchFieldValue("projecttype")));
		

		private TextField _summary;
		/// <summary>Represents the  field (a8afcc63-4732-43d7-a426-1e9c0d683eea).</summary>
		[IndexFieldAttribute("summary_t")]
		public TextField Summary => _summary ?? (_summary = new TextField(new LazyField(() => InnerItem.Fields["{a8afcc63-4732-43d7-a426-1e9c0d683eea}"], "/sitecore/templates/feature/projects/_Project", "Summary"), GetSearchFieldValue("summary_t")));
		

		private ImageField _thumbImage;
		/// <summary>Represents the  field (370db987-b2b2-4b02-8ed1-abb7ab22fd09).</summary>
		[IndexFieldAttribute("thumbimage")]
		public ImageField ThumbImage => _thumbImage ?? (_thumbImage = new ImageField(new LazyField(() => InnerItem.Fields["{370db987-b2b2-4b02-8ed1-abb7ab22fd09}"], "/sitecore/templates/feature/projects/_Project", "ThumbImage"), GetSearchFieldValue("thumbimage")));
		

	}

	public class ProjectInitializer : ITemplateInitializer
	{
		public ID InitializesTemplateId => new ID("{07ef3625-2856-4c66-a9a6-ac31216a56a6}");

		public IStandardTemplateItem CreateInstance(Item innerItem)
		{
			return new Project(innerItem);
		}

		public IStandardTemplateItem CreateInstanceFromSearch(IDictionary<string, string> searchFields)
		{
			return new Project(searchFields);
		}
	}
}

namespace Helix.Feature.Projects
{
	using global::Sitecore.ContentSearch;
	using global::Sitecore.Data;
	using global::Sitecore.Data.Items;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{51e1374a-c4a6-45db-b431-cd2a7c57c1c6}", "", "Feature.Projects")]
    [SitecoreType]
	public interface IProjectCollection : IGlassBase
	{
		
		/// <summary>Represents the  field (13a331f7-e588-4768-b2aa-a140de6335b6).</summary>
		[IndexFieldAttribute("projects_sm")]
		IItemReferenceListField Projects { get; }

	}

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	public class ProjectCollection : IGlassBase, IProjectCollection
	{
		public ProjectCollection(Item innerItem) : base(innerItem)
		{
		}

		public ProjectCollection(IDictionary<string, string> searchFields) : base(searchFields)
		{
		}

		/// <summary>The name of the Sitecore Template that this class represents</summary>
		public static string TemplateName => "_ProjectCollection";

		/// <summary>The ID of the Sitecore Template that this class represents</summary>
		public static ID ItemTemplateId => new ID("{51e1374a-c4a6-45db-b431-cd2a7c57c1c6}");

		/// <summary>The ID of the Sitecore Template that this class represents</summary>
		public override ID TemplateId => ItemTemplateId;

		
		private ItemReferenceListField _projects;
		/// <summary>Represents the  field (13a331f7-e588-4768-b2aa-a140de6335b6).</summary>
		[IndexFieldAttribute("projects_sm")]
		public ItemReferenceListField Projects => _projects ?? (_projects = new ItemReferenceListField(new LazyField(() => InnerItem.Fields["{13a331f7-e588-4768-b2aa-a140de6335b6}"], "/sitecore/templates/feature/projects/_ProjectCollection", "Projects"), GetSearchFieldValue("projects_sm")));
		

	}

	public class ProjectCollectionInitializer : ITemplateInitializer
	{
		public ID InitializesTemplateId => new ID("{51e1374a-c4a6-45db-b431-cd2a7c57c1c6}");

		public IStandardTemplateItem CreateInstance(Item innerItem)
		{
			return new ProjectCollection(innerItem);
		}

		public IStandardTemplateItem CreateInstanceFromSearch(IDictionary<string, string> searchFields)
		{
			return new ProjectCollection(searchFields);
		}
	}
}



// Helix.Feature.Projects.Project (/sitecore/templates/feature/projects/_Project 07ef3625-2856-4c66-a9a6-ac31216a56a6)
	// FullText (7c39e7f5-5b3c-495c-a01b-c9f2ebbbdc87)
		// Type: Rich Text
		// Section: Project Information
		// Sort Order: 300
		// Source: 
	// Name (0eb2de30-2d40-4f3a-a781-8e8efe96d2f0)
		// Type: Single-Line Text
		// Section: Project Information
		// Sort Order: 100
		// Source: 
	// PrimaryImage (616279a1-24f9-43e5-bb4c-5ce2da6269e9)
		// Type: Image
		// Section: Project Information
		// Sort Order: 500
		// Source: 
	// ProjectType (b3711e42-e538-4982-bcc5-0a0b6d44ffc7)
		// Type: Droplist
		// Section: Project Information
		// Sort Order: 600
		// Source: 
	// Summary (a8afcc63-4732-43d7-a426-1e9c0d683eea)
		// Type: Multi-Line Text
		// Section: Project Information
		// Sort Order: 200
		// Source: 
	// ThumbImage (370db987-b2b2-4b02-8ed1-abb7ab22fd09)
		// Type: Image
		// Section: Project Information
		// Sort Order: 400
		// Source: 

// Helix.Feature.Projects.ProjectCollection (/sitecore/templates/feature/projects/_ProjectCollection 51e1374a-c4a6-45db-b431-cd2a7c57c1c6)
	// Projects (13a331f7-e588-4768-b2aa-a140de6335b6)
		// Type: Treelist
		// Section: Information
		// Sort Order: 100
		// Source: 

