
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Services
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{6c04b521-7bea-438f-98f0-390bdf658704}", "", "Feature.Services")]
    [SitecoreType(TemplateId = Helix.Feature.Services.Templates.Service.TemplateIdString)]
	public partial interface IService : IGlassBase
	{
		
		/// <summary>Represents the  field (bfef580b-29a9-4272-92b5-bcbd6a2cc40e).</summary>
        [SitecoreField(FieldName = Helix.Feature.Services.Templates.Service.Fields.Summary_FieldName)]
		string Summary { get; }

		/// <summary>Represents the  field (163077ce-3d6a-4c31-b186-0df86977f56d).</summary>
        [SitecoreField(FieldName = Helix.Feature.Services.Templates.Service.Fields.Thumbnail_FieldName)]
		Image Thumbnail { get; }

		/// <summary>Represents the  field (625a3008-6bc4-4aec-aab5-0198e90dd316).</summary>
        [SitecoreField(FieldName = Helix.Feature.Services.Templates.Service.Fields.Title_FieldName)]
		string Title { get; }

	}

}

namespace Helix.Feature.Services
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{80cc9251-6a08-4008-a18f-5eec17105a7a}", "", "Feature.Services")]
    [SitecoreType(TemplateId = Helix.Feature.Services.Templates.ServiceCollection.TemplateIdString)]
	public partial interface IServiceCollection : IGlassBase
	{
		
		/// <summary>Represents the  field (abc6e742-74a9-41b2-8b1f-bc2e2956cdfc).</summary>
        [SitecoreField(FieldName = Helix.Feature.Services.Templates.ServiceCollection.Fields.Services_FieldName)]
		IEnumerable<Guid> Services { get; }

	}

}




namespace Helix.Feature.Services
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct Service
		{
            public const string TemplateIdString = "6c04b521-7bea-438f-98f0-390bdf658704";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Summary = new ID("bfef580b-29a9-4272-92b5-bcbd6a2cc40e");
				public const string Summary_FieldName = "Summary";

				public static readonly ID Thumbnail = new ID("163077ce-3d6a-4c31-b186-0df86977f56d");
				public const string Thumbnail_FieldName = "Thumbnail";

				public static readonly ID Title = new ID("625a3008-6bc4-4aec-aab5-0198e90dd316");
				public const string Title_FieldName = "Title";

			}
		}

		public struct ServiceCollection
		{
            public const string TemplateIdString = "80cc9251-6a08-4008-a18f-5eec17105a7a";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Services = new ID("abc6e742-74a9-41b2-8b1f-bc2e2956cdfc");
				public const string Services_FieldName = "Services";

			}
		}

	}
}

// Helix.Feature.Services.Service (/sitecore/templates/feature/services/_Service 6c04b521-7bea-438f-98f0-390bdf658704)
	// Summary (bfef580b-29a9-4272-92b5-bcbd6a2cc40e)
		// Type: Multi-Line Text
		// Section: Service Information
		// Sort Order: 200
		// Source: 
	// Thumbnail (163077ce-3d6a-4c31-b186-0df86977f56d)
		// Type: Image
		// Section: Images
		// Sort Order: 100
		// Source: 
	// Title (625a3008-6bc4-4aec-aab5-0198e90dd316)
		// Type: Single-Line Text
		// Section: Service Information
		// Sort Order: 100
		// Source: 

// Helix.Feature.Services.ServiceCollection (/sitecore/templates/feature/services/_ServiceCollection 80cc9251-6a08-4008-a18f-5eec17105a7a)
	// Services (abc6e742-74a9-41b2-8b1f-bc2e2956cdfc)
		// Type: Treelist
		// Section: Information
		// Sort Order: 100
		// Source: 

