---
ID: "984b6cfc-3b99-469f-9c84-71991fbf77f0"
Parent: "faf72982-5dcf-4804-9817-c1a2533bae29"
Template: "faf72982-5dcf-4804-9817-c1a2533bae29"
Path: /sitecore/templates/foundation/Taxonomy/LookupCategory/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180315T164934Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
