---
ID: "c797489d-758a-4f83-8d31-9e9708534f94"
Parent: "6cd1c785-c4d2-4c0a-a34c-bf4e6f01cb16"
Template: "6cd1c785-c4d2-4c0a-a34c-bf4e6f01cb16"
Path: /sitecore/templates/feature/members/_Member/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180423T150446Z
    - ID: "2bd94ac0-f867-440f-a908-88b686f5a3eb"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
