---
ID: "84b87b44-bb4f-40d7-8c13-f5331e22dd58"
Parent: "c112bb85-8aa3-4743-9ab8-337a812a7b9d"
Template: "38cba701-087d-42a2-b3c4-b2b9269cc95b"
Path: /sitecore/content/agency/settings
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Settings
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180315T172000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
