
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Helix.Feature.Members
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{6cd1c785-c4d2-4c0a-a34c-bf4e6f01cb16}", "", "Feature.Members")]
    [SitecoreType(TemplateId = Helix.Feature.Members.Templates.Member.TemplateIdString)]
	public partial interface IMember : IGlassBase
	{
		
		/// <summary>Represents the  field (34d9f40c-8f1a-4129-8e00-763b4c088de5).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.FacebookUrl_FieldName)]
		string FacebookUrl { get; }

		/// <summary>Represents the  field (9e414380-f718-4ca8-8cd3-728193a3d0dd).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.LinkedInUrl_FieldName)]
		string LinkedInUrl { get; }

		/// <summary>Represents the  field (2bd94ac0-f867-440f-a908-88b686f5a3eb).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.Name_FieldName)]
		string Name { get; }

		/// <summary>Represents the  field (65f99714-e05d-489c-a939-70b31f3a0616).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.Position_FieldName)]
		string Position { get; }

		/// <summary>Represents the  field (97299c06-4bce-4ba5-9781-4c61edc2ca9d).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.Thumbnail_FieldName)]
		Image Thumbnail { get; }

		/// <summary>Represents the  field (a4d04cf8-f6ca-4606-af15-4d2e2dcfe2cd).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.Member.Fields.TwitterUrl_FieldName)]
		string TwitterUrl { get; }

	}

}

namespace Helix.Feature.Members
{
    using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
    using Helix.Foundation.ORM.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;

	/// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
	///[RepresentsSitecoreTemplateAttribute("{d7915809-474a-4f03-8ebe-6f0a1063e7f6}", "", "Feature.Members")]
    [SitecoreType(TemplateId = Helix.Feature.Members.Templates.MemberCollection.TemplateIdString)]
	public partial interface IMemberCollection : IGlassBase
	{
		
		/// <summary>Represents the  field (94196fce-a936-41d3-8a68-e1280a2caa3e).</summary>
        [SitecoreField(FieldName = Helix.Feature.Members.Templates.MemberCollection.Fields.Members_FieldName)]
		IEnumerable<Guid> Members { get; }

	}

}




namespace Helix.Feature.Members
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct Member
		{
            public const string TemplateIdString = "6cd1c785-c4d2-4c0a-a34c-bf4e6f01cb16";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID FacebookUrl = new ID("34d9f40c-8f1a-4129-8e00-763b4c088de5");
				public const string FacebookUrl_FieldName = "FacebookUrl";

				public static readonly ID LinkedInUrl = new ID("9e414380-f718-4ca8-8cd3-728193a3d0dd");
				public const string LinkedInUrl_FieldName = "LinkedInUrl";

				public static readonly ID Name = new ID("2bd94ac0-f867-440f-a908-88b686f5a3eb");
				public const string Name_FieldName = "Name";

				public static readonly ID Position = new ID("65f99714-e05d-489c-a939-70b31f3a0616");
				public const string Position_FieldName = "Position";

				public static readonly ID Thumbnail = new ID("97299c06-4bce-4ba5-9781-4c61edc2ca9d");
				public const string Thumbnail_FieldName = "Thumbnail";

				public static readonly ID TwitterUrl = new ID("a4d04cf8-f6ca-4606-af15-4d2e2dcfe2cd");
				public const string TwitterUrl_FieldName = "TwitterUrl";

			}
		}

		public struct MemberCollection
		{
            public const string TemplateIdString = "d7915809-474a-4f03-8ebe-6f0a1063e7f6";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Members = new ID("94196fce-a936-41d3-8a68-e1280a2caa3e");
				public const string Members_FieldName = "Members";

			}
		}

	}
}

// Helix.Feature.Members.Member (/sitecore/templates/feature/members/_Member 6cd1c785-c4d2-4c0a-a34c-bf4e6f01cb16)
	// FacebookUrl (34d9f40c-8f1a-4129-8e00-763b4c088de5)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 400
		// Source: 
	// LinkedInUrl (9e414380-f718-4ca8-8cd3-728193a3d0dd)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 500
		// Source: 
	// Name (2bd94ac0-f867-440f-a908-88b686f5a3eb)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 100
		// Source: 
	// Position (65f99714-e05d-489c-a939-70b31f3a0616)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 200
		// Source: 
	// Thumbnail (97299c06-4bce-4ba5-9781-4c61edc2ca9d)
		// Type: Image
		// Section: Images
		// Sort Order: 100
		// Source: 
	// TwitterUrl (a4d04cf8-f6ca-4606-af15-4d2e2dcfe2cd)
		// Type: Single-Line Text
		// Section: Information
		// Sort Order: 300
		// Source: 

// Helix.Feature.Members.MemberCollection (/sitecore/templates/feature/members/_MemberCollection d7915809-474a-4f03-8ebe-6f0a1063e7f6)
	// Members (94196fce-a936-41d3-8a68-e1280a2caa3e)
		// Type: Treelist
		// Section: Member Information
		// Sort Order: 100
		// Source: 

